import asyncio
import os
from dotenv import load_dotenv
from app.services import QueryProcessingService

# Load environment variables
load_dotenv()

async def verify_rag():
    print("--- Verifying RAG Implementation ---")
    
    # Check API Key
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        print("ERROR: GROQ_API_KEY not found in environment.")
        return

    print("GROQ_API_KEY found.")

    service = QueryProcessingService()
    query = "What is the punishment for theft?"
    
    print(f"\nQuerying: '{query}'")
    try:
        result = await service.process_query(query)
        
        print("\n--- Result ---")
        print(f"Question: {result['question']}")
        
        print(f"\nSources ({len(result['sources'])} found):")
        for i, source in enumerate(result['sources']):
            print(f"  {i+1}. {source}")
            
        print("\nAnswer (Generated by Groq):")
        print(result['answer'])
        
        if result['sources'] and result['answer']:
            print("\nSUCCESS: Data was retrieved and an answer was generated.")
        else:
            print("\nWARNING: Missing sources or answer.")
            
    except Exception as e:
        print(f"\nERROR: {e}")

if __name__ == "__main__":
    asyncio.run(verify_rag())
